params:
   
    depth: 3
    epochs: 200
    learning_rate: 0.0003
    batch_size: 4
    patch_x: 64
    patch_y: 64
    kern_size: 3
    n_patches_per_image: 32
    startfilter: 32
    erosion_iterations: 0
    generate_npz: True
    validation_split: 0.01
    n_channel_in: 1
    train_unet: True
    train_star: False
    train_loss: 'mae'
    file_type: '*.tif'
    min_size: 1
    min_size_mask: 10
    max_size: 1000000
    n_tiles: [4,4]
    axes: 'YX'

aug_params:
       

        gauss_filter_size: 0
        #choices for augmentation below are 1 or 2 or None
        flip_axis: 1
        shift_axis: 1
        zoom_axis: 1
        #shift range can be between -1 and 1 (-1 and 1 will translate the pixels completely out), zoom range > 0
        shift_range: 0.2 
        zoom_range: 2
        rotate_axis: 1
        rotation_angles: [20, 40, 60, 90, 120, 160] 
        pattern : [".tif", ".TIFF", ".TIF", ".png"] 
        sigma : 10
        mean : 0
        alpha_affine : 1.8
        alpha : 3
        distribution : 'Both'    
    

defaults:
   - files_vollseg: vollseg_files
   - paths_vollseg: vollseg_paths_jean_zay
   - _self_ 
       
